const more = {};
// This is really a json file, but editing as js has better tools/commenting
/**
 * This file would normally be generated by the compiler and gives the mapping of binary values to the more human-readable values.  In this scenario, the file would be complete with no 'null' values (because the compiler
 * knows the name of every binary object in the resulting binary config file).
 * One the other hand, during the reverse engineering process, we assuming we have Example.HarmonyConfig.bin we should be able to generate Example.HarmonyConfig.raw.json from it.  If we then
 * use the next decompiler to generatoe Example.HarmonyConfig.json, we will have a file with auto-generated names (e.g. StateVariable0).  We should be able to make educated guesses about what those names should be
 * (e.g. from the menu context) that will allow us to update Example.HarmonyConfig.map.json, and thereby generate a more human-readable Example.HarmonyConfig.json file.
 */
const FirstGuess = {
  $Metadata: {
    SourceFile: "Sample.HarmonyConfig.json", // Maybe Sample.HarmonyConfig.bin if it was reversed from binary
  },
  InfraredDevices: [
    {
      Name: "Television",
    },
    null,
    {
      Name: "DVD Player",
    },
    ,
    ...more,
  ],
  Menus: [
    {
      Name: "Home",
    },
    null,
    null,
    ...more,
  ],
  StateVariables: [
    {
      Name: "Watch TV",
      Type: "Activity",
    },
    null,
    {
      Name: "Television Power",
      Type: "DevicePower",
    },
    {
      Name: "Television Input",
      Type: "DeviceInput",
    },
    null,
    ...more,
  ],
  ...more,
};
