"""Emit an ImHex pattern that annotates one specific config.

    python tools/export_hexpat.py samples/harmony525/config.bin

The shared type definitions live in patterns/harmony.hexpat and are copied in
verbatim, so the file this writes is self-contained: open it in ImHex next to
the config and the whole blob is annotated, not just its header.

The reason for generating rather than writing a pattern that parses the file
itself is that most of these structures cannot be found by scanning. They are
reached by following pointers, and several are distinguished only by where a
pointer lands rather than by anything in their own bytes - a bitmap is a
bitmap because a block header points at it, and a five-byte key table read at
a stride of four dissolves into noise. The decompiler already does that work,
so this just writes down what it found.

Which also means the output inherits the decompiler's honesty: a region it
calls Opaque is one nobody has explained yet, and the regions tile the blob
completely, so there is nowhere for something to hide unnoticed.
"""
import sys
from pathlib import Path

import _paths  # noqa: F401
import hconfig

TYPES_END = "// === END OF TYPES ==="
PATTERNS = Path(__file__).resolve().parent.parent / "patterns"


def shared_types() -> str:
    text = (PATTERNS / "harmony.hexpat").read_text(encoding="utf-8")
    i = text.find(TYPES_END)
    if i == -1:
        raise SystemExit(f"{TYPES_END!r} not found in patterns/harmony.hexpat")
    return text[:i].rstrip() + "\n"


def placement(r: dict, name: str):
    """The ImHex declaration for one region, or None to leave it unplaced."""
    kind = r["kind"]
    n = hconfig.region_length(r)

    if kind == "blob_header":
        pad = len(bytes.fromhex(r["padding"]))
        return f"BlobHeader<{r['section_count']}, {pad}> {name}"
    if kind == "blob_footer":
        return f"char {name}[4]"
    if kind == "name_table":
        return f"NameTable<{len(r['records'])}> {name}"
    if kind == "pointer_table":
        head = r["count_width"] + len(bytes.fromhex(r.get("header", "")))
        return f"PointerTable<{head}, {len(r['targets'])}> {name}"
    if kind == "key_table":
        stride = r.get("entry_stride", 4)
        return f"KeyTable{stride}<{len(r['entries'])}> {name}"
    if kind == "record_header":
        return f"RecordHeader<{len(r['targets'])}> {name}"
    if kind == "action_list":
        return f"ActionList<{len(r['instructions'])}> {name}"
    if kind == "block_header":
        return f"BlockHeader {name}"
    if kind == "reference":
        return f"Reference {name}"
    if kind == "record_trailer":
        return f"RecordTrailer {name}"
    if kind == "bitmap":
        return f"Bitmap {name}"
    if kind in ("opaque", "section"):
        return f"Opaque<{n}> {name}"
    raise SystemExit(f"no ImHex type for region kind {kind!r}")


def export(path: Path) -> str:
    raw = path.read_bytes()
    doc = hconfig.decompile(raw, path.name)
    blob = doc["blob"]
    regions = blob["regions"]

    xml, _, binary = hconfig.split_container(raw)
    if xml is not None:
        note = (f"// Generated from {path.name}, which is an .EZHex. The offsets\n"
                f"// below are into the BLOB, so point ImHex at the binary part\n"
                f"// only - tools/split_ezhex.py writes it out, or skip the first\n"
                f"// {len(xml) + 2} bytes of this file.\n")
    else:
        note = f"// Generated from {path.name}.\n"

    counts = {}
    for r in regions:
        counts[r["kind"]] = counts.get(r["kind"], 0) + 1
    decoded = sum(hconfig.region_length(r) for r in regions
                  if r["kind"] not in ("opaque", "section"))

    out = [shared_types()]
    out.append("// " + "-" * 71)
    out.append("// Placements, generated by tools/export_hexpat.py. Do not edit by hand:")
    out.append("// regenerate instead, and put anything worth keeping into the")
    out.append("// recognisers in tools/hconfig.py so the round-trip test can check it.")
    out.append("//")
    out.append(note.rstrip())
    out.append("//")
    out.append(f"// blob size   {blob['size']} B")
    out.append(f"// sha256      {doc['source']['sha256']}")
    out.append(f"// decoded     {decoded} B, {100 * decoded / blob['size']:.2f}%")
    out.append("//")
    for kind in sorted(counts):
        out.append(f"//   {counts[kind]:>5}  {kind}")
    out.append("")

    section = object()
    for i, r in enumerate(regions):
        if r.get("section", None) != section:
            section = r.get("section", None)
            out.append("")
            out.append(f"// ---- section {section} " + "-" * 40
                       if section is not None else
                       "// ---- not covered by the section table " + "-" * 25)
        name = f"{r['kind']}_{r['offset']:06x}"
        out.append(f"{placement(r, name)} @ 0x{r['offset']:06X};")

    out.append("")
    return "\n".join(out)


def main(argv):
    if len(argv) != 2:
        print(__doc__)
        return 2
    src = Path(argv[1])
    text = export(src)

    # samples/harmony525/config.bin -> harmony525.hexpat
    # samples/arch8/Update-2.EZHex -> arch8-Update-2.hexpat
    stem = src.name.split(".")[0]
    folder = src.resolve().parent.name
    name = folder if stem in ("config", "blob") else f"{folder}-{stem}"
    dest = PATTERNS / f"{name}.hexpat"
    dest.write_text(text, encoding="utf-8")
    print(f"{dest}  ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
